services:
  dq_backend:
    container_name: dq_backend
    build: .
    command: ["gunicorn", "-k", "egg:meinheld#gunicorn_worker", "-c", "gunicorn_conf.py", "app:app"]
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0      # fondamentale, altrimenti il container non è raggiungibile
      # - PORT=5000
      - LOG_LEVEL=info
      - WORKERS_PER_CORE=2
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: dequa_nw
    external: true