name: dequa
channels:
  - conda-forge
  - defaults
dependencies:
  # General
  - python=3.9.2
  - pip=24.3.1
  - ipython=8.18.1
  - ipdb=0.13.7
  - colorlog=5.0.1
  - python-dotenv=0.16.0
  # Network
  - graph-tool=2.37
  - networkx=2.5
  - geopy=2.1.0
  # Flask
  - flask=2.1.2
  - flask-admin=1.5.7
  - sqlalchemy=1.4.3
  - flask-sqlalchemy=2.5.1
  - flask-jwt-extended=3.19.0
  - flask-restful=0.3.9
  - flask-apscheduler=1.12.3
  - flask-migrate=2.4.0
  - flask-cors=3.0.8
  - flask-mail=0.9.1
  - flask-wtf=1.0.1
  - email-validator=1.1.2
  - flask-security=3.0.0
  - werkzeug=2.0.1
  - jinja2=3.0.3
  - wtforms=3.0.1
  # Server
  - gunicorn=20.1.0
  # Other utils
  - git=2.30.2
  - gitpython=3.1.14
  - fuzzywuzzy=0.18.0
  - pyjwt=1.6.1
  - pyyaml=6.0
  - pip:
    - greenlet==0.4.16
    - meinheld==1.0.2
    - geoalchemy2==0.9.2
    - psycopg2==2.9.3
    - flask-shell-ipython==0.4.1
    - flask-track-usage==2.0.0
    - git+https://github.com/De-Qua/dequa-graph.git

