name: dequa
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython=7.22.0
  - python-dotenv=0.16.0
  - flask-admin=1.5.7
  - pip=20.3.1
  - ipdb=0.13.7
  - flask-sqlalchemy=2.5.1
  - flask-jwt-extended=3.19.0
  - pyjwt=1.6.1
  - flask-restful=0.3.9
  - werkzeug=2.0.1
  - networkx=2.5
  - flask=2.1.2
  - graph-tool=2.37
  - pandas=1.2.3
  - colorlog=5.0.1
  - flask-security=3.0.0
  - gitpython=3.1.14
  - jinja2=3.0.3
  - shapely=1.7.1
  - python=3.9.2
  - geopy=2.1.0
  - fuzzywuzzy=0.18.0
  - flask-apscheduler=1.12.3
  - flask-migrate=2.4.0
  - git=2.30.2
  - flask-mail=0.9.1
  - email-validator=1.1.2
  - flask-cors=3.0.8
  - gunicorn=20.1.0
  - pyyaml=6.0
  - geoalchemy2=0.9.2
  - meinheld=1.0.2
  - pip:
    - flask-shell-ipython==0.4.1
    - flask-track-usage==2.0.0
