"""Poi OSM tags as json

Revision ID: 2fda207ad66e
Revises: b40608a96352
Create Date: 2026-02-13 09:29:00.059204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fda207ad66e'
down_revision = 'b40608a96352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Contribution')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Datatype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Datatype')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Geouser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Geouser')),
    sa.UniqueConstraint('email', name=op.f('uq_Geouser_email')),
    sa.UniqueConstraint('nickname', name=op.f('uq_Geouser_nickname')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Language')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Visibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Visibility')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('apis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apis')),
    sa.UniqueConstraint('name', name=op.f('uq_apis_name')),
    info={'bind_key': 'internal'}
    )
    op.create_table('error_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_error_groups_name')),
    info={'bind_key': 'config_data'}
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.Column('searched_string', sa.String(length=128), nullable=True),
    sa.Column('searched_start', sa.String(length=128), nullable=True),
    sa.Column('searched_end', sa.String(length=128), nullable=True),
    sa.Column('found_string', sa.String(length=128), nullable=True),
    sa.Column('found_start', sa.String(length=128), nullable=True),
    sa.Column('found_end', sa.String(length=128), nullable=True),
    sa.Column('feedback', sa.String(length=512), nullable=True),
    sa.Column('json', sa.String(), nullable=True),
    sa.Column('start_coord', sa.String(), nullable=True),
    sa.Column('end_coord', sa.String(), nullable=True),
    sa.Column('report', sa.String(length=256), nullable=True),
    sa.Column('solved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedbacks')),
    info={'bind_key': 'collected_data'}
    )
    op.create_table('flask_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('ua_browser', sa.String(length=16), nullable=True),
    sa.Column('ua_language', sa.String(length=16), nullable=True),
    sa.Column('ua_platform', sa.String(length=16), nullable=True),
    sa.Column('ua_version', sa.String(length=16), nullable=True),
    sa.Column('blueprint', sa.String(length=16), nullable=True),
    sa.Column('view_args', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('remote_addr', sa.String(length=24), nullable=True),
    sa.Column('xforwardedfor', sa.String(length=24), nullable=True),
    sa.Column('authorization', sa.Boolean(), nullable=True),
    sa.Column('ip_info', sa.String(length=1024), nullable=True),
    sa.Column('path', sa.String(length=32), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('track_var', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flask_usage')),
    info={'bind_key': 'collected_data'}
    )
    op.create_table('ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_title', sa.String(length=128), nullable=True),
    sa.Column('idea_short_description', sa.String(length=256), nullable=True),
    sa.Column('num_of_votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ideas')),
    info={'bind_key': 'collected_data'}
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages')),
    sa.UniqueConstraint('code', name=op.f('uq_languages_code')),
    sa.UniqueConstraint('name', name=op.f('uq_languages_name')),
    info={'bind_key': 'config_data'}
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name')),
    info={'bind_key': 'internal'}
    )
    op.create_table('runtime_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('error_type', sa.String(length=256), nullable=True),
    sa.Column('error_message', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('method', sa.String(length=256), nullable=True),
    sa.Column('browser', sa.String(length=256), nullable=True),
    sa.Column('pickle', sa.String(length=256), nullable=True),
    sa.Column('report', sa.String(length=256), nullable=True),
    sa.Column('solved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runtime_errors')),
    info={'bind_key': 'collected_data'}
    )
    op.create_table('short_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=True),
    sa.Column('shortcode', sa.String(length=25), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('generation_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_short_url')),
    info={'bind_key': 'internal'}
    )
    op.create_table('token_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_types')),
    sa.UniqueConstraint('type', name=op.f('uq_token_types_type')),
    info={'bind_key': 'internal'}
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=160), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    info={'bind_key': 'internal'}
    )
    op.create_table('Datagroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('keyname', sa.String(length=255), nullable=False),
    sa.Column('geouser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geouser_id'], ['Geouser.id'], name=op.f('fk_Datagroup_geouser_id_Geouser')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Datagroup')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('date_last_modification', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('default_icon', sa.String(length=255), nullable=True),
    sa.Column('geouser_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('visibility_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['Contribution.id'], name=op.f('fk_Layer_contribution_id_Contribution')),
    sa.ForeignKeyConstraint(['geouser_id'], ['Geouser.id'], name=op.f('fk_Layer_geouser_id_Geouser')),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_Layer_language_id_Language')),
    sa.ForeignKeyConstraint(['visibility_id'], ['Visibility.id'], name=op.f('fk_Layer_visibility_id_Visibility')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Layer')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemDatagroupParameterValueTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_LayerItemDatagroupParameterValueTranslation_language_id_Language')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemDatagroupParameterValueTranslation')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('geouser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geouser_id'], ['Geouser.id'], name=op.f('fk_Tag_geouser_id_Geouser')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Tag')),
    sa.UniqueConstraint('name', name=op.f('uq_Tag_name')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('error_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['error_groups.id'], name=op.f('fk_error_codes_group_id_error_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_error_codes_code')),
    info={'bind_key': 'config_data'}
    )
    op.create_table('roles_users',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('roles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], name=op.f('fk_roles_users_roles_id_roles')),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name=op.f('fk_roles_users_users_id_users')),
    info={'bind_key': 'internal', 'tablename': 'roles_users'}
    )
    op.create_table('short_url_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shorturl_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shorturl_id'], ['short_url.id'], name=op.f('fk_short_url_counter_shorturl_id_short_url')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_short_url_counter')),
    info={'bind_key': 'internal'}
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=True),
    sa.Column('jti', sa.String(length=36), nullable=True),
    sa.Column('token_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['token_type_id'], ['token_types.id'], name=op.f('fk_tokens_token_type_id_token_types')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens')),
    info={'bind_key': 'internal'}
    )
    op.create_table('types_apis',
    sa.Column('token_types_id', sa.Integer(), nullable=True),
    sa.Column('apis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apis_id'], ['apis.id'], name=op.f('fk_types_apis_apis_id_apis')),
    sa.ForeignKeyConstraint(['token_types_id'], ['token_types.id'], name=op.f('fk_types_apis_token_types_id_token_types')),
    info={'bind_key': 'internal', 'tablename': 'types_apis'}
    )
    op.create_table('LayerDatagroup',
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.Column('datagroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datagroup_id'], ['Datagroup.id'], name=op.f('fk_LayerDatagroup_datagroup_id_Datagroup')),
    sa.ForeignKeyConstraint(['layer_id'], ['Layer.id'], name=op.f('fk_LayerDatagroup_layer_id_Layer')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('date_last_modification', sa.DateTime(), nullable=True),
    sa.Column('geouser_id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.Column('datagroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datagroup_id'], ['Datagroup.id'], name=op.f('fk_LayerItem_datagroup_id_Datagroup')),
    sa.ForeignKeyConstraint(['geouser_id'], ['Geouser.id'], name=op.f('fk_LayerItem_geouser_id_Geouser')),
    sa.ForeignKeyConstraint(['layer_id'], ['Layer.id'], name=op.f('fk_LayerItem_layer_id_Layer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItem')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemDatagroupParameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyname', sa.String(length=255), nullable=False),
    sa.Column('datagroup_id', sa.Integer(), nullable=False),
    sa.Column('datatype_id', sa.Integer(), nullable=False),
    sa.Column('paramval_translation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['datagroup_id'], ['Datagroup.id'], name=op.f('fk_LayerItemDatagroupParameter_datagroup_id_Datagroup')),
    sa.ForeignKeyConstraint(['datatype_id'], ['Datatype.id'], name=op.f('fk_LayerItemDatagroupParameter_datatype_id_Datatype')),
    sa.ForeignKeyConstraint(['paramval_translation_id'], ['LayerItemDatagroupParameterValueTranslation.id'], name=op.f('fk_LayerItemDatagroupParameter_paramval_translation_id_LayerItemDatagroupParameterValueTranslation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemDatagroupParameter')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerTag',
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['Layer.id'], name=op.f('fk_LayerTag_layer_id_Layer')),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], name=op.f('fk_LayerTag_tag_id_Tag')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_LayerTranslation_language_id_Language')),
    sa.ForeignKeyConstraint(['layer_id'], ['Layer.id'], name=op.f('fk_LayerTranslation_layer_id_Layer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerTranslation')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('error_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['error_codes.id'], name=op.f('fk_error_translation_code_id_error_codes')),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_error_translation_language_id_languages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_translation')),
    info={'bind_key': 'config_data'}
    )
    op.create_table('token_api_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], name=op.f('fk_token_api_counters_api_id_apis')),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('fk_token_api_counters_token_id_tokens')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_api_counters')),
    info={'bind_key': 'internal'}
    )
    op.create_table('LayerItemDatagroupParameterTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_LayerItemDatagroupParameterTranslation_language_id_Language')),
    sa.ForeignKeyConstraint(['parameter_id'], ['LayerItemDatagroupParameter.id'], name=op.f('fk_LayerItemDatagroupParameterTranslation_parameter_id_LayerItemDatagroupParameter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemDatagroupParameterTranslation')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemDatagroupParameterValue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer_item_id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.Column('paramval_translation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['layer_item_id'], ['LayerItem.id'], name=op.f('fk_LayerItemDatagroupParameterValue_layer_item_id_LayerItem')),
    sa.ForeignKeyConstraint(['parameter_id'], ['LayerItemDatagroupParameter.id'], name=op.f('fk_LayerItemDatagroupParameterValue_parameter_id_LayerItemDatagroupParameter')),
    sa.ForeignKeyConstraint(['paramval_translation_id'], ['LayerItemDatagroupParameterValueTranslation.id'], name=op.f('fk_LayerItemDatagroupParameterValue_paramval_translation_id_LayerItemDatagroupParameterValueTranslation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemDatagroupParameterValue')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemTag',
    sa.Column('layer_item_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layer_item_id'], ['LayerItem.id'], name=op.f('fk_LayerItemTag_layer_item_id_LayerItem')),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], name=op.f('fk_LayerItemTag_tag_id_Tag')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=255), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('layer_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_LayerItemTranslation_language_id_Language')),
    sa.ForeignKeyConstraint(['layer_item_id'], ['LayerItem.id'], name=op.f('fk_LayerItemTranslation_layer_item_id_LayerItem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemTranslation')),
    info={'bind_key': 'geotag'}
    )
    op.drop_index('idx_area_shape', table_name='area', postgresql_using='gist')
    op.drop_index('idx_location_shape', table_name='location', postgresql_using='gist')
    op.drop_index('idx_neighborhood_shape', table_name='neighborhood', postgresql_using='gist')
    op.add_column('poi', sa.Column('osm_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_street_shape', table_name='street', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_street_shape', 'street', ['shape'], unique=False, postgresql_using='gist')
    op.drop_column('poi', 'osm_tags')
    op.create_index('idx_neighborhood_shape', 'neighborhood', ['shape'], unique=False, postgresql_using='gist')
    op.create_index('idx_location_shape', 'location', ['shape'], unique=False, postgresql_using='gist')
    op.create_index('idx_area_shape', 'area', ['shape'], unique=False, postgresql_using='gist')
    op.drop_table('LayerItemTranslation')
    op.drop_table('LayerItemTag')
    op.drop_table('LayerItemDatagroupParameterValue')
    op.drop_table('LayerItemDatagroupParameterTranslation')
    op.drop_table('token_api_counters')
    op.drop_table('error_translation')
    op.drop_table('LayerTranslation')
    op.drop_table('LayerTag')
    op.drop_table('LayerItemDatagroupParameter')
    op.drop_table('LayerItem')
    op.drop_table('LayerDatagroup')
    op.drop_table('types_apis')
    op.drop_table('tokens')
    op.drop_table('short_url_counter')
    op.drop_table('roles_users')
    op.drop_table('error_codes')
    op.drop_table('Tag')
    op.drop_table('LayerItemDatagroupParameterValueTranslation')
    op.drop_table('Layer')
    op.drop_table('Datagroup')
    op.drop_table('users')
    op.drop_table('token_types')
    op.drop_table('short_url')
    op.drop_table('runtime_errors')
    op.drop_table('roles')
    op.drop_table('languages')
    op.drop_table('ideas')
    op.drop_table('flask_usage')
    op.drop_table('feedbacks')
    op.drop_table('error_groups')
    op.drop_table('apis')
    op.drop_table('Visibility')
    op.drop_table('Language')
    op.drop_table('Geouser')
    op.drop_table('Datatype')
    op.drop_table('Contribution')
    # ### end Alembic commands ###
