words = {
    'specials': [
        'oro benon',
        'pitura freska',
        'ara che ben',
        'beo come el sol',
        'papa nero',
        'buon pranzo',
        'marubio in vista',
        'pope oe',
        'bea vecio',
        'bea vecia',
        'stracaganase',
        'risi e bisi',
        'xe riva nadal',
        'sgrafamasegni',
        'duri i banchi',
        'na bruta banda',
        'pin floi',
        'suca baruca',
        'picinin',
        'marghera'
    ],
    'specials_after_num': [
        'ombre de rosso',
        'ombre de bianco',
        'caffe lisci',
        'caffe lunghi',
        'caffe macchiati',
        'cappuccini',
        'caffe e brioche',
        'paninetti',
        'birrette',
        'cicchetti',
        'spritz campari',
        'spritz aperol',
        'spritz cynar',
        'gatti in fila per tre',
        'posti barca',
        'colombi in fila',
        'turisti in acqua',
        'trabaccoli',
        'pantegane',
        'barche picae',
        'barche all ai',
        'minuti di ritardo',
        'ore in coda'
    ],
    'names': [
        'altana',
        'amigo',
        'amiga',
        'ancuo',
        'baba',
        'bacan',
        'barba',
        'bagigio',
        'bagolo',
        'bar'
        'biavarol',
        'bigolo',
        'bocolo',
        'bovolo',
        'butiro',
        'carega',
        'caorlina',
        'caigo',
        'caicio',
        'cheba',
        'ciapa',
        'cocai',
        'cogoma',
        'comio',
        'crecola',
        'deo',
        'dindio',
        'doge',
        'erbaria',
        'fio',
        'fia',
        'freschin',
        'goto',
        'megio',
        'moeca',
        'musso',
        'pittima',
        'puteo',
        'ruga',
        'sandolo',
        'gondola',
        'toppa',
        'scafa',
        'scagi',
        'schei',
        'tera',
        'tecia',
        'tola',
        'zebedei',
        'verze',
        'ghebi',
        'more',
        'vecio',
        'caorio',
        'busia',
        'bateo',
        'batela',
        'becher',
        'caegher',
        'bricola',
        'ciacole',
        'peoci',
        'schie',
        'rio',
        'pope',
        'piron',
        'squero',
        'voga',
        'barena',
        'forcola',
        'fontego',
        'proa',
        'poppa',
        'ombra',
        'canton',
        'spriss',
        'scarsea',
        'bueo',
        'bocia',
        'palina',
        'persego',
        'salizada',
    ],
    'adjectives': [
        'marso',
        'marsa',
        'onto',
        'onta'
        'beo',
        'bea',
        'in saor',
        'pieno',
        'piena',
        'vodo',
        'voda',
        'matta',
        'matto',
        'castron',
        'castrona',
        'giassada',
        'imbriago',
        'imbriaga',
        'ransio',
        'picada',
        'roto',
        'rota',
        'brutto',
        'brutta'
    ],
    'verbs': [
        'magna',
        'ndemo',
        'tasi',
        'ara',
        'ciapa',
        'cori',
        'tira',
        'voga',
        'dime',
        'dighe',
        'dame',
        'varda',
        'compro',
        'vendo',
        'butto',
        'cerco',
        'ti ga',
        'gavemo',
        'ti me da',
        'bevemo',
        'magnemo',
        'supia',
        'tol',
        'tolemo'
    ]
}
