"""empty message

Revision ID: 154e159e545a
Revises: ae136ec16c3b
Create Date: 2020-11-24 00:16:57.190412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154e159e545a'
down_revision = 'ae136ec16c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Feedbacks', schema=None) as batch_op:
        batch_op.drop_column('end_coord')
        batch_op.drop_column('start_coord')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_coord', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('end_coord', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
