"""empty message

Revision ID: 2122c842840f
Revises: 
Create Date: 2020-05-26 01:40:11.130162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2122c842840f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('shape', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_area'))
    )
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_area_name'), ['name'], unique=False)

    op.create_table('neighborhood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('shape', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_neighborhood'))
    )
    with op.batch_alter_table('neighborhood', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_neighborhood_name'), ['name'], unique=False)

    op.create_table('poi_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poi_category'))
    )
    with op.batch_alter_table('poi_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poi_category_name'), ['name'], unique=True)

    op.create_table('street',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('name_alt', sa.String(length=64), nullable=True),
    sa.Column('name_spe', sa.String(length=64), nullable=True),
    sa.Column('name_den', sa.String(length=64), nullable=True),
    sa.Column('shape', sa.PickleType(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='check_score'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_street')),
    sa.UniqueConstraint('shape', name=op.f('uq_street_shape'))
    )
    with op.batch_alter_table('street', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_street_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_street_name_alt'), ['name_alt'], unique=False)
        batch_op.create_index(batch_op.f('ix_street_name_den'), ['name_den'], unique=False)
        batch_op.create_index(batch_op.f('ix_street_name_spe'), ['name_spe'], unique=False)

    op.create_table('area_streets',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], name=op.f('fk_area_streets_area_id_area')),
    sa.ForeignKeyConstraint(['street_id'], ['street.id'], name=op.f('fk_area_streets_street_id_street')),
    sa.PrimaryKeyConstraint('area_id', 'street_id', name=op.f('pk_area_streets'))
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('neighborhood_id', sa.Integer(), nullable=False),
    sa.Column('housenumber', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhood.id'], name=op.f('fk_location_neighborhood_id_neighborhood')),
    sa.ForeignKeyConstraint(['street_id'], ['street.id'], name=op.f('fk_location_street_id_street')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location'))
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_housenumber'), ['housenumber'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_longitude'), ['longitude'], unique=False)

    op.create_table('poi_category_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subtype', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['poi_category.id'], name=op.f('fk_poi_category_type_category_id_poi_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poi_category_type'))
    )
    with op.batch_alter_table('poi_category_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poi_category_type_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_poi_category_type_subtype'), ['subtype'], unique=False)

    op.create_table('streets_neighborhoods',
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('neighborhood_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhood.id'], name=op.f('fk_streets_neighborhoods_neighborhood_id_neighborhood')),
    sa.ForeignKeyConstraint(['street_id'], ['street.id'], name=op.f('fk_streets_neighborhoods_street_id_street')),
    sa.PrimaryKeyConstraint('street_id', 'neighborhood_id', name=op.f('pk_streets_neighborhoods'))
    )
    op.create_table('poi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('name_alt', sa.String(length=128), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('categorytype_id', sa.Integer(), nullable=True),
    sa.Column('opening_hours', sa.String(length=256), nullable=True),
    sa.Column('wheelchair', sa.String(length=8), nullable=True),
    sa.Column('toilets', sa.Boolean(), nullable=True),
    sa.Column('toilets_wheelchair', sa.Boolean(), nullable=True),
    sa.Column('wikipedia', sa.String(length=128), nullable=True),
    sa.Column('atm', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('last_change', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='check_score'),
    sa.ForeignKeyConstraint(['categorytype_id'], ['poi_category_type.id'], name=op.f('fk_poi_categorytype_id_poi_category_type')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_poi_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poi'))
    )
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poi_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_poi_name_alt'), ['name_alt'], unique=False)

    op.create_table('poi_types',
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], name=op.f('fk_poi_types_poi_id_poi')),
    sa.ForeignKeyConstraint(['type_id'], ['poi_category_type.id'], name=op.f('fk_poi_types_type_id_poi_category_type')),
    sa.PrimaryKeyConstraint('poi_id', 'type_id', name=op.f('pk_poi_types'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poi_types')
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poi_name_alt'))
        batch_op.drop_index(batch_op.f('ix_poi_name'))

    op.drop_table('poi')
    op.drop_table('streets_neighborhoods')
    with op.batch_alter_table('poi_category_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poi_category_type_subtype'))
        batch_op.drop_index(batch_op.f('ix_poi_category_type_name'))

    op.drop_table('poi_category_type')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_longitude'))
        batch_op.drop_index(batch_op.f('ix_location_latitude'))
        batch_op.drop_index(batch_op.f('ix_location_housenumber'))

    op.drop_table('location')
    op.drop_table('area_streets')
    with op.batch_alter_table('street', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_street_name_spe'))
        batch_op.drop_index(batch_op.f('ix_street_name_den'))
        batch_op.drop_index(batch_op.f('ix_street_name_alt'))
        batch_op.drop_index(batch_op.f('ix_street_name'))

    op.drop_table('street')
    with op.batch_alter_table('poi_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poi_category_name'))

    op.drop_table('poi_category')
    with op.batch_alter_table('neighborhood', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_neighborhood_name'))

    op.drop_table('neighborhood')
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_area_name'))

    op.drop_table('area')
    # ### end Alembic commands ###
