"""empty message

Revision ID: 31ae988abb11
Revises: 
Create Date: 2020-05-08 18:19:01.072937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ae988abb11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neighborhood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zipcode')
    )
    op.create_index(op.f('ix_neighborhood_name'), 'neighborhood', ['name'], unique=False)
    op.create_table('poi_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poi_category_name'), 'poi_category', ['name'], unique=True)
    op.create_table('poi_category_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subtype', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['poi_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poi_category_type_name'), 'poi_category_type', ['name'], unique=False)
    op.create_index(op.f('ix_poi_category_type_subtype'), 'poi_category_type', ['subtype'], unique=False)
    op.create_table('street',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('name_alt', sa.String(length=64), nullable=True),
    sa.Column('neighborhood_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhood.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_street_name'), 'street', ['name'], unique=False)
    op.create_index(op.f('ix_street_name_alt'), 'street', ['name_alt'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.Column('housenumber', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['street_id'], ['street.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_housenumber'), 'location', ['housenumber'], unique=False)
    op.create_index(op.f('ix_location_latitude'), 'location', ['latitude'], unique=False)
    op.create_index(op.f('ix_location_longitude'), 'location', ['longitude'], unique=False)
    op.create_table('poi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('categorytype_id', sa.Integer(), nullable=True),
    sa.Column('opening_hours', sa.String(length=256), nullable=True),
    sa.Column('wheelchair', sa.String(length=8), nullable=True),
    sa.Column('last_change', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categorytype_id'], ['poi_category_type.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poi_name'), 'poi', ['name'], unique=False)
    op.create_table('poi_types',
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['poi_category_type.id'], ),
    sa.PrimaryKeyConstraint('poi_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poi_types')
    op.drop_index(op.f('ix_poi_name'), table_name='poi')
    op.drop_table('poi')
    op.drop_index(op.f('ix_location_longitude'), table_name='location')
    op.drop_index(op.f('ix_location_latitude'), table_name='location')
    op.drop_index(op.f('ix_location_housenumber'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_street_name_alt'), table_name='street')
    op.drop_index(op.f('ix_street_name'), table_name='street')
    op.drop_table('street')
    op.drop_index(op.f('ix_poi_category_type_subtype'), table_name='poi_category_type')
    op.drop_index(op.f('ix_poi_category_type_name'), table_name='poi_category_type')
    op.drop_table('poi_category_type')
    op.drop_index(op.f('ix_poi_category_name'), table_name='poi_category')
    op.drop_table('poi_category')
    op.drop_index(op.f('ix_neighborhood_name'), table_name='neighborhood')
    op.drop_table('neighborhood')
    # ### end Alembic commands ###
