"""empty message

Revision ID: 350b23cba52e
Revises: 86a2d8448531
Create Date: 2021-01-21 00:08:15.405500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350b23cba52e'
down_revision = '86a2d8448531'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_trackusage():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_trackusage():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_token_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token'))
    )
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jti', sa.VARCHAR(length=36), nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), nullable=False),
    sa.Column('expires', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('revoked IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_token_blacklist_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_token_blacklist')
    )
    op.drop_table('token')
    # ### end Alembic commands ###


def upgrade_ideas():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_ideas():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_feed_err():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_feed_err():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

