"""empty message

Revision ID: 4767cee951b8
Revises: 0badb603069e
Create Date: 2020-05-23 18:07:41.645986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4767cee951b8'
down_revision = '0badb603069e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi', sa.Column('atm', sa.Boolean(), nullable=True))
    op.add_column('poi', sa.Column('name_alt', sa.String(length=128), nullable=True))
    op.add_column('poi', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('poi', sa.Column('toilets', sa.Boolean(), nullable=True))
    op.add_column('poi', sa.Column('toilets_wheelchair', sa.Boolean(), nullable=True))
    op.add_column('poi', sa.Column('wikipedia', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_poi_name_alt'), 'poi', ['name_alt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poi_name_alt'), table_name='poi')
    op.drop_column('poi', 'wikipedia')
    op.drop_column('poi', 'toilets_wheelchair')
    op.drop_column('poi', 'toilets')
    op.drop_column('poi', 'phone')
    op.drop_column('poi', 'name_alt')
    op.drop_column('poi', 'atm')
    # ### end Alembic commands ###
