"""empty message

Revision ID: 5e459d89ceb0
Revises: e3872c2a0bd0
Create Date: 2020-05-22 17:09:25.786079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e459d89ceb0'
down_revision = 'e3872c2a0bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('neighborhood', schema=None) as batch_op:
        batch_op.alter_column('zipcode',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('street', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shape', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('street', schema=None) as batch_op:
        batch_op.drop_column('shape')

    with op.batch_alter_table('neighborhood', schema=None) as batch_op:
        batch_op.alter_column('zipcode',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
