"""empty message

Revision ID: 60271875d363
Revises: 699c339a1361
Create Date: 2020-11-24 00:28:25.545660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60271875d363'
down_revision = '699c339a1361'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_trackusage():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_trackusage():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ideas():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_ideas():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_feed_err():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_coord', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('start_coord', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade_feed_err():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Feedbacks', schema=None) as batch_op:
        batch_op.drop_column('start_coord')
        batch_op.drop_column('end_coord')

    # ### end Alembic commands ###

