"""empty message

Revision ID: 699c339a1361
Revises: 154e159e545a
Create Date: 2020-11-24 00:19:39.581867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699c339a1361'
down_revision = '154e159e545a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_coord', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('start_coord', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Feedbacks', schema=None) as batch_op:
        batch_op.drop_column('start_coord')
        batch_op.drop_column('end_coord')

    # ### end Alembic commands ###
