"""tolto nullable da street_id in location

Revision ID: 8085c088291e
Revises: c15a6d33c81c
Create Date: 2020-06-01 12:39:00.546128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8085c088291e'
down_revision = 'c15a6d33c81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('street_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('street_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
