"""empty message

Revision ID: 9bf1ecc6ba71
Revises: bdc610b2910d
Create Date: 2021-03-30 23:44:59.406109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf1ecc6ba71'
down_revision = 'bdc610b2910d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_trackusage():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_trackusage():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_type')
    op.drop_table('token')
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), nullable=True),
    sa.Column('jti', sa.VARCHAR(length=36), nullable=True),
    sa.Column('token_type_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), nullable=True),
    sa.Column('expires', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('revoked IN (0, 1)', name='ck_token_revoked'),
    sa.ForeignKeyConstraint(['token_type_id'], ['token_type.id'], name='fk_token_token_type_id_token_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_token_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_token')
    )
    op.create_table('token_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_token_type'),
    sa.UniqueConstraint('type', name='uq_token_type_type')
    )
    # ### end Alembic commands ###


def upgrade_errors():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_errors():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ideas():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_ideas():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_feed_err():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_feed_err():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

