"""aggiunti campi osm in poi

Revision ID: a6f4d4c2ea9d
Revises: 8085c088291e
Create Date: 2020-06-01 13:32:04.768919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f4d4c2ea9d'
down_revision = '8085c088291e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('osm_other_tags', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('osm_type', sa.String(length=8), nullable=True))
        batch_op.drop_constraint('uq_poi_osm_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_poi_osm_id', ['osm_id'])
        batch_op.drop_column('osm_type')
        batch_op.drop_column('osm_other_tags')

    # ### end Alembic commands ###
