"""empty message

Revision ID: ae136ec16c3b
Revises: 91c51f2bc232
Create Date: 2020-11-23 18:04:14.985709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae136ec16c3b'
down_revision = '91c51f2bc232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('error_type', sa.String(length=256), nullable=True),
    sa.Column('error_message', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('method', sa.String(length=256), nullable=True),
    sa.Column('browser', sa.String(length=256), nullable=True),
    sa.Column('pickle', sa.String(length=256), nullable=True),
    sa.Column('report', sa.String(length=256), nullable=True),
    sa.Column('solved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Errors'))
    )
    op.create_table('Feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.Column('searched_string', sa.String(length=128), nullable=True),
    sa.Column('searched_start', sa.String(length=128), nullable=True),
    sa.Column('searched_end', sa.String(length=128), nullable=True),
    sa.Column('found_string', sa.String(length=128), nullable=True),
    sa.Column('found_start', sa.String(length=128), nullable=True),
    sa.Column('found_end', sa.String(length=128), nullable=True),
    sa.Column('feedback', sa.String(length=512), nullable=True),
    sa.Column('json', sa.String(), nullable=True),
    sa.Column('start_coord', sa.String(), nullable=True),
    sa.Column('end_coord', sa.String(), nullable=True),
    sa.Column('report', sa.String(length=256), nullable=True),
    sa.Column('solved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Feedbacks'))
    )
    op.create_table('Ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_title', sa.String(length=128), nullable=True),
    sa.Column('idea_short_description', sa.String(length=256), nullable=True),
    sa.Column('num_of_votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Ideas'))
    )
    op.create_table('flask_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('ua_browser', sa.String(length=16), nullable=True),
    sa.Column('ua_language', sa.String(length=16), nullable=True),
    sa.Column('ua_platform', sa.String(length=16), nullable=True),
    sa.Column('ua_version', sa.String(length=16), nullable=True),
    sa.Column('blueprint', sa.String(length=16), nullable=True),
    sa.Column('view_args', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('remote_addr', sa.String(length=24), nullable=True),
    sa.Column('xforwardedfor', sa.String(length=24), nullable=True),
    sa.Column('authorization', sa.Boolean(), nullable=True),
    sa.Column('ip_info', sa.String(length=1024), nullable=True),
    sa.Column('path', sa.String(length=32), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('track_var', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flask_usage'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('roles_users',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('roles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], name=op.f('fk_roles_users_roles_id_roles')),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name=op.f('fk_roles_users_users_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('flask_usage')
    op.drop_table('Ideas')
    op.drop_table('Feedbacks')
    op.drop_table('Errors')
    # ### end Alembic commands ###
