"""empty message

Revision ID: b40608a96352
Revises: e8ae71cb9434
Create Date: 2024-11-03 15:50:15.834775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40608a96352'
down_revision = 'e8ae71cb9434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Contribution')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Datatype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Datatype')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Geouser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Geouser')),
    sa.UniqueConstraint('email', name=op.f('uq_Geouser_email')),
    sa.UniqueConstraint('nickname', name=op.f('uq_Geouser_nickname')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Language')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Visibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Visibility')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Datagroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('keyname', sa.String(length=255), nullable=False),
    sa.Column('geouser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geouser_id'], ['Geouser.id'], name=op.f('fk_Datagroup_geouser_id_Geouser')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Datagroup')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('date_last_modification', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('default_icon', sa.String(length=255), nullable=True),
    sa.Column('geouser_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('visibility_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['Contribution.id'], name=op.f('fk_Layer_contribution_id_Contribution')),
    sa.ForeignKeyConstraint(['geouser_id'], ['Geouser.id'], name=op.f('fk_Layer_geouser_id_Geouser')),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_Layer_language_id_Language')),
    sa.ForeignKeyConstraint(['visibility_id'], ['Visibility.id'], name=op.f('fk_Layer_visibility_id_Visibility')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Layer')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemDatagroupParameterValueTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_LayerItemDatagroupParameterValueTranslation_language_id_Language')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemDatagroupParameterValueTranslation')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('geouser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geouser_id'], ['Geouser.id'], name=op.f('fk_Tag_geouser_id_Geouser')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Tag')),
    sa.UniqueConstraint('name', name=op.f('uq_Tag_name')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerDatagroup',
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.Column('datagroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datagroup_id'], ['Datagroup.id'], name=op.f('fk_LayerDatagroup_datagroup_id_Datagroup')),
    sa.ForeignKeyConstraint(['layer_id'], ['Layer.id'], name=op.f('fk_LayerDatagroup_layer_id_Layer')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('date_last_modification', sa.DateTime(), nullable=True),
    sa.Column('geouser_id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.Column('datagroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datagroup_id'], ['Datagroup.id'], name=op.f('fk_LayerItem_datagroup_id_Datagroup')),
    sa.ForeignKeyConstraint(['geouser_id'], ['Geouser.id'], name=op.f('fk_LayerItem_geouser_id_Geouser')),
    sa.ForeignKeyConstraint(['layer_id'], ['Layer.id'], name=op.f('fk_LayerItem_layer_id_Layer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItem')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemDatagroupParameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyname', sa.String(length=255), nullable=False),
    sa.Column('datagroup_id', sa.Integer(), nullable=False),
    sa.Column('datatype_id', sa.Integer(), nullable=False),
    sa.Column('paramval_translation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['datagroup_id'], ['Datagroup.id'], name=op.f('fk_LayerItemDatagroupParameter_datagroup_id_Datagroup')),
    sa.ForeignKeyConstraint(['datatype_id'], ['Datatype.id'], name=op.f('fk_LayerItemDatagroupParameter_datatype_id_Datatype')),
    sa.ForeignKeyConstraint(['paramval_translation_id'], ['LayerItemDatagroupParameterValueTranslation.id'], name=op.f('fk_LayerItemDatagroupParameter_paramval_translation_id_LayerItemDatagroupParameterValueTranslation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemDatagroupParameter')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerTag',
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['Layer.id'], name=op.f('fk_LayerTag_layer_id_Layer')),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], name=op.f('fk_LayerTag_tag_id_Tag')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_LayerTranslation_language_id_Language')),
    sa.ForeignKeyConstraint(['layer_id'], ['Layer.id'], name=op.f('fk_LayerTranslation_layer_id_Layer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerTranslation')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemDatagroupParameterTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_LayerItemDatagroupParameterTranslation_language_id_Language')),
    sa.ForeignKeyConstraint(['parameter_id'], ['LayerItemDatagroupParameter.id'], name=op.f('fk_LayerItemDatagroupParameterTranslation_parameter_id_LayerItemDatagroupParameter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemDatagroupParameterTranslation')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemDatagroupParameterValue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer_item_id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.Column('paramval_translation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['layer_item_id'], ['LayerItem.id'], name=op.f('fk_LayerItemDatagroupParameterValue_layer_item_id_LayerItem')),
    sa.ForeignKeyConstraint(['parameter_id'], ['LayerItemDatagroupParameter.id'], name=op.f('fk_LayerItemDatagroupParameterValue_parameter_id_LayerItemDatagroupParameter')),
    sa.ForeignKeyConstraint(['paramval_translation_id'], ['LayerItemDatagroupParameterValueTranslation.id'], name=op.f('fk_LayerItemDatagroupParameterValue_paramval_translation_id_LayerItemDatagroupParameterValueTranslation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemDatagroupParameterValue')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemTag',
    sa.Column('layer_item_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layer_item_id'], ['LayerItem.id'], name=op.f('fk_LayerItemTag_layer_item_id_LayerItem')),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], name=op.f('fk_LayerItemTag_tag_id_Tag')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=255), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('layer_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_LayerItemTranslation_language_id_Language')),
    sa.ForeignKeyConstraint(['layer_item_id'], ['LayerItem.id'], name=op.f('fk_LayerItemTranslation_layer_item_id_LayerItem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemTranslation')),
    info={'bind_key': 'geotag'}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LayerItemTranslation')
    op.drop_table('LayerItemTag')
    op.drop_table('LayerItemDatagroupParameterValue')
    op.drop_table('LayerItemDatagroupParameterTranslation')
    op.drop_table('LayerTranslation')
    op.drop_table('LayerTag')
    op.drop_table('LayerItemDatagroupParameter')
    op.drop_table('LayerItem')
    op.drop_table('LayerDatagroup')
    op.drop_table('Tag')
    op.drop_table('LayerItemDatagroupParameterValueTranslation')
    op.drop_table('Layer')
    op.drop_table('Datagroup')
    op.drop_table('Visibility')
    op.drop_table('Language')
    op.drop_table('Geouser')
    op.drop_table('Datatype')
    op.drop_table('Contribution')
    # ### end Alembic commands ###
