"""added osm_id to POI

Revision ID: c15a6d33c81c
Revises: e320e6d15422
Create Date: 2020-05-30 19:19:41.115680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15a6d33c81c'
down_revision = 'e320e6d15422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('osm_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_poi_osm_id'), ['osm_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_poi_osm_id'), type_='unique')
        batch_op.drop_column('osm_id')

    # ### end Alembic commands ###
