"""shape not nullabe

Revision ID: e320e6d15422
Revises: c773632321ef
Create Date: 2020-05-30 16:14:59.181319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e320e6d15422'
down_revision = 'c773632321ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('shape',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('shape',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###
