"""area e geometrie

Revision ID: e3872c2a0bd0
Revises: 31ae988abb11
Create Date: 2020-05-22 16:55:36.467957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3872c2a0bd0'
down_revision = '31ae988abb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('shape', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_name'), 'area', ['name'], unique=False)
    op.create_table('area_streets',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['street_id'], ['street.id'], ),
    sa.PrimaryKeyConstraint('area_id', 'street_id')
    )
    op.alter_column('location', 'latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('location', 'longitude',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('neighborhood', 'zipcode',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('street', sa.Column('shape', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('street', 'shape')
    op.alter_column('neighborhood', 'zipcode',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location', 'longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('location', 'latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.drop_table('area_streets')
    op.drop_index(op.f('ix_area_name'), table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###
