"""empty message

Revision ID: e8ae71cb9434
Revises: 50eb53636e76
Create Date: 2021-07-10 11:34:03.228222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ae71cb9434'
down_revision = '50eb53636e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('housenumber_num', sa.Integer(), nullable=False))
    op.alter_column('address', 'housenumber',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_address_housenumber'), 'address', ['housenumber'], unique=False)
    op.drop_index('idx_area_shape', table_name='area')
    op.drop_index('idx_location_shape', table_name='location')
    op.drop_constraint('fk_location_street_id_street', 'location', type_='foreignkey')
    op.drop_constraint('fk_location_neighborhood_id_neighborhood', 'location', type_='foreignkey')
    op.drop_column('location', 'neighborhood_id')
    op.drop_column('location', 'street_id')
    op.drop_index('idx_neighborhood_shape', table_name='neighborhood')
    op.drop_index('idx_street_shape', table_name='street')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_street_shape', 'street', ['shape'], unique=False)
    op.create_index('idx_neighborhood_shape', 'neighborhood', ['shape'], unique=False)
    op.add_column('location', sa.Column('street_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('neighborhood_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_location_neighborhood_id_neighborhood', 'location', 'neighborhood', ['neighborhood_id'], ['id'])
    op.create_foreign_key('fk_location_street_id_street', 'location', 'street', ['street_id'], ['id'])
    op.create_index('idx_location_shape', 'location', ['shape'], unique=False)
    op.create_index('idx_area_shape', 'area', ['shape'], unique=False)
    op.drop_index(op.f('ix_address_housenumber'), table_name='address')
    op.alter_column('address', 'housenumber',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('address', 'housenumber_num')
    # ### end Alembic commands ###
