"""CurrentData: add column last_check

Revision ID: 1af36c297b03
Revises: cf5010e0a8c9
Create Date: 2025-10-15 00:12:29.870147

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1af36c297b03'
down_revision = 'cf5010e0a8c9'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_collected_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_collected_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_config_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_config_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_internal():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_internal():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_geotag():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_geotag():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_data_versions():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('current_data', 'updated_at', new_column_name='graph_updated_at')
    op.add_column('current_data', sa.Column('graph_check_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade_data_versions():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('current_data', 'graph_updated_at', new_column_name='updated_at')
    op.drop_column('current_data', 'graph_check_at')
    # ### end Alembic commands ###

