"""Remove not nullable constraint on curr data

Revision ID: 38ece6e05c81
Revises: 1af36c297b03
Create Date: 2025-10-21 01:11:54.648938

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '38ece6e05c81'
down_revision = '1af36c297b03'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_collected_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_collected_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_config_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_config_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_internal():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_internal():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_geotag():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_geotag():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_data_versions():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('current_data', 'street_graph_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('current_data', 'waterbus_graph_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('current_data', 'water_graph_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('current_data', 'tide_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade_data_versions():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('current_data', 'tide_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('current_data', 'water_graph_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('current_data', 'waterbus_graph_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('current_data', 'street_graph_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###

