"""initial schema

Revision ID: b8c5b24b3acc
Revises: 
Create Date: 2026-09-10 13:28:11.262181

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8c5b24b3acc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('shape', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_area'))
    )
    op.create_index(op.f('ix_area_name'), 'area', ['name'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('shape', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location'))
    )
    op.create_index(op.f('ix_location_latitude'), 'location', ['latitude'], unique=False)
    op.create_index(op.f('ix_location_longitude'), 'location', ['longitude'], unique=False)
    op.create_table('neighborhood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('shape', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_neighborhood'))
    )
    op.create_index(op.f('ix_neighborhood_name'), 'neighborhood', ['name'], unique=False)
    op.create_table('poi_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poi_category'))
    )
    op.create_index(op.f('ix_poi_category_name'), 'poi_category', ['name'], unique=True)
    op.create_table('street',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('name_alt', sa.String(length=64), nullable=True),
    sa.Column('name_spe', sa.String(length=64), nullable=True),
    sa.Column('name_den', sa.String(length=64), nullable=True),
    sa.Column('shape', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='check_score'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_street'))
    )
    op.create_index(op.f('ix_street_name'), 'street', ['name'], unique=False)
    op.create_index(op.f('ix_street_name_alt'), 'street', ['name_alt'], unique=False)
    op.create_index(op.f('ix_street_name_den'), 'street', ['name_den'], unique=False)
    op.create_index(op.f('ix_street_name_spe'), 'street', ['name_spe'], unique=False)
    op.create_table('tide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_station', sa.String(length=8), nullable=True),
    sa.Column('station', sa.String(length=64), nullable=True),
    sa.Column('short_name', sa.String(length=16), nullable=True),
    sa.Column('latDMSN', sa.Float(), nullable=True),
    sa.Column('lonDMSE', sa.Float(), nullable=True),
    sa.Column('latDDN', sa.Float(), nullable=True),
    sa.Column('lonDDE', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tide'))
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('housenumber_num', sa.Integer(), nullable=False),
    sa.Column('housenumber_sub', sa.String(length=1), nullable=True),
    sa.Column('housenumber', sa.String(length=8), nullable=True),
    sa.Column('address_neigh', sa.String(length=64), nullable=True),
    sa.Column('address_street', sa.String(length=128), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_address_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address'))
    )
    op.create_index(op.f('ix_address_address_neigh'), 'address', ['address_neigh'], unique=False)
    op.create_index(op.f('ix_address_address_street'), 'address', ['address_street'], unique=False)
    op.create_index(op.f('ix_address_housenumber'), 'address', ['housenumber'], unique=False)
    op.create_table('poi_category_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subtype', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['poi_category.id'], name=op.f('fk_poi_category_type_category_id_poi_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poi_category_type'))
    )
    op.create_index(op.f('ix_poi_category_type_name'), 'poi_category_type', ['name'], unique=False)
    op.create_index(op.f('ix_poi_category_type_subtype'), 'poi_category_type', ['subtype'], unique=False)
    op.create_table('poi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('name_alt', sa.String(length=128), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('categorytype_id', sa.Integer(), nullable=True),
    sa.Column('opening_hours', sa.String(length=256), nullable=True),
    sa.Column('wheelchair', sa.String(length=8), nullable=True),
    sa.Column('toilets', sa.Boolean(), nullable=True),
    sa.Column('toilets_wheelchair', sa.Boolean(), nullable=True),
    sa.Column('wikipedia', sa.String(length=128), nullable=True),
    sa.Column('atm', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('last_change', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('osm_type', sa.String(length=8), nullable=True),
    sa.Column('osm_id', sa.BigInteger(), nullable=True),
    sa.Column('osm_other_tags', sa.String(), nullable=True),
    sa.Column('osm_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='check_score'),
    sa.ForeignKeyConstraint(['categorytype_id'], ['poi_category_type.id'], name=op.f('fk_poi_categorytype_id_poi_category_type')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_poi_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poi'))
    )
    op.create_index(op.f('ix_poi_name'), 'poi', ['name'], unique=False)
    op.create_index(op.f('ix_poi_name_alt'), 'poi', ['name_alt'], unique=False)
    op.create_table('poi_types',
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], name=op.f('fk_poi_types_poi_id_poi')),
    sa.ForeignKeyConstraint(['type_id'], ['poi_category_type.id'], name=op.f('fk_poi_types_type_id_poi_category_type')),
    sa.PrimaryKeyConstraint('poi_id', 'type_id', name=op.f('pk_poi_types')),
    info={'bind_key': None}
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poi_types')
    op.drop_index(op.f('ix_poi_name_alt'), table_name='poi')
    op.drop_index(op.f('ix_poi_name'), table_name='poi')
    op.drop_table('poi')
    op.drop_index(op.f('ix_poi_category_type_subtype'), table_name='poi_category_type')
    op.drop_index(op.f('ix_poi_category_type_name'), table_name='poi_category_type')
    op.drop_table('poi_category_type')
    op.drop_index(op.f('ix_address_housenumber'), table_name='address')
    op.drop_index(op.f('ix_address_address_street'), table_name='address')
    op.drop_index(op.f('ix_address_address_neigh'), table_name='address')
    op.drop_table('address')
    op.drop_table('tide')
    op.drop_index(op.f('ix_street_name_spe'), table_name='street')
    op.drop_index(op.f('ix_street_name_den'), table_name='street')
    op.drop_index(op.f('ix_street_name_alt'), table_name='street')
    op.drop_index(op.f('ix_street_name'), table_name='street')
    op.drop_table('street')
    op.drop_index(op.f('ix_poi_category_name'), table_name='poi_category')
    op.drop_table('poi_category')
    op.drop_index(op.f('ix_neighborhood_name'), table_name='neighborhood')
    op.drop_table('neighborhood')
    op.drop_index(op.f('ix_location_longitude'), table_name='location')
    op.drop_index(op.f('ix_location_latitude'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_area_name'), table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###


def upgrade_collected_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.Column('searched_string', sa.String(length=128), nullable=True),
    sa.Column('searched_start', sa.String(length=128), nullable=True),
    sa.Column('searched_end', sa.String(length=128), nullable=True),
    sa.Column('found_string', sa.String(length=128), nullable=True),
    sa.Column('found_start', sa.String(length=128), nullable=True),
    sa.Column('found_end', sa.String(length=128), nullable=True),
    sa.Column('feedback', sa.String(length=512), nullable=True),
    sa.Column('json', sa.String(), nullable=True),
    sa.Column('start_coord', sa.String(), nullable=True),
    sa.Column('end_coord', sa.String(), nullable=True),
    sa.Column('report', sa.String(length=256), nullable=True),
    sa.Column('solved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedbacks')),
    info={'bind_key': 'collected_data'}
    )
    op.create_table('ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_title', sa.String(length=128), nullable=True),
    sa.Column('idea_short_description', sa.String(length=256), nullable=True),
    sa.Column('num_of_votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ideas')),
    info={'bind_key': 'collected_data'}
    )
    op.create_table('runtime_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('error_type', sa.String(length=256), nullable=True),
    sa.Column('error_message', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('method', sa.String(length=256), nullable=True),
    sa.Column('browser', sa.String(length=256), nullable=True),
    sa.Column('pickle', sa.String(length=256), nullable=True),
    sa.Column('report', sa.String(length=256), nullable=True),
    sa.Column('solved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runtime_errors')),
    info={'bind_key': 'collected_data'}
    )
    op.alter_column('flask_usage', 'url',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_collected_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flask_usage', 'url',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_table('runtime_errors')
    op.drop_table('ideas')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###


def upgrade_config_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_groups')),
    sa.UniqueConstraint('name'),
    info={'bind_key': 'config_data'}
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages')),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    info={'bind_key': 'config_data'}
    )
    op.create_table('error_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['error_groups.id'], name=op.f('fk_error_codes_group_id_error_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_codes')),
    sa.UniqueConstraint('code'),
    info={'bind_key': 'config_data'}
    )
    op.create_table('error_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['error_codes.id'], name=op.f('fk_error_translation_code_id_error_codes')),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_error_translation_language_id_languages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_translation')),
    info={'bind_key': 'config_data'}
    )
    # ### end Alembic commands ###


def downgrade_config_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('error_translation')
    op.drop_table('error_codes')
    op.drop_table('languages')
    op.drop_table('error_groups')
    # ### end Alembic commands ###


def upgrade_internal():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apis')),
    sa.UniqueConstraint('name'),
    info={'bind_key': 'internal'}
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name'),
    info={'bind_key': 'internal'}
    )
    op.create_table('short_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=True),
    sa.Column('shortcode', sa.String(length=25), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('generation_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_short_url')),
    info={'bind_key': 'internal'}
    )
    op.create_table('token_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_types')),
    sa.UniqueConstraint('type'),
    info={'bind_key': 'internal'}
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=160), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email'),
    info={'bind_key': 'internal'}
    )
    op.create_table('roles_users',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('roles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], name=op.f('fk_roles_users_roles_id_roles')),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name=op.f('fk_roles_users_users_id_users')),
    info={'bind_key': 'internal', 'tablename': 'roles_users'}
    )
    op.create_table('short_url_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shorturl_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shorturl_id'], ['short_url.id'], name=op.f('fk_short_url_counter_shorturl_id_short_url')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_short_url_counter')),
    info={'bind_key': 'internal'}
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=True),
    sa.Column('jti', sa.String(length=36), nullable=True),
    sa.Column('token_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['token_type_id'], ['token_types.id'], name=op.f('fk_tokens_token_type_id_token_types')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens')),
    info={'bind_key': 'internal'}
    )
    op.create_table('types_apis',
    sa.Column('token_types_id', sa.Integer(), nullable=True),
    sa.Column('apis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apis_id'], ['apis.id'], name=op.f('fk_types_apis_apis_id_apis')),
    sa.ForeignKeyConstraint(['token_types_id'], ['token_types.id'], name=op.f('fk_types_apis_token_types_id_token_types')),
    info={'bind_key': 'internal', 'tablename': 'types_apis'}
    )
    op.create_table('token_api_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], name=op.f('fk_token_api_counters_api_id_apis')),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('fk_token_api_counters_token_id_tokens')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_api_counters')),
    info={'bind_key': 'internal'}
    )
    # ### end Alembic commands ###


def downgrade_internal():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_api_counters')
    op.drop_table('types_apis')
    op.drop_table('tokens')
    op.drop_table('short_url_counter')
    op.drop_table('roles_users')
    op.drop_table('users')
    op.drop_table('token_types')
    op.drop_table('short_url')
    op.drop_table('roles')
    op.drop_table('apis')
    # ### end Alembic commands ###


def upgrade_geotag():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Contribution')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Datatype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Datatype')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Geouser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Geouser')),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname'),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Language')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Visibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Visibility')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Datagroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('keyname', sa.String(length=255), nullable=False),
    sa.Column('geouser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geouser_id'], ['Geouser.id'], name=op.f('fk_Datagroup_geouser_id_Geouser')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Datagroup')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('date_last_modification', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('default_icon', sa.String(length=255), nullable=True),
    sa.Column('geouser_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('visibility_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['Contribution.id'], name=op.f('fk_Layer_contribution_id_Contribution')),
    sa.ForeignKeyConstraint(['geouser_id'], ['Geouser.id'], name=op.f('fk_Layer_geouser_id_Geouser')),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_Layer_language_id_Language')),
    sa.ForeignKeyConstraint(['visibility_id'], ['Visibility.id'], name=op.f('fk_Layer_visibility_id_Visibility')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Layer')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('Tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('geouser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geouser_id'], ['Geouser.id'], name=op.f('fk_Tag_geouser_id_Geouser')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Tag')),
    sa.UniqueConstraint('name'),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerDatagroup',
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.Column('datagroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datagroup_id'], ['Datagroup.id'], name=op.f('fk_LayerDatagroup_datagroup_id_Datagroup')),
    sa.ForeignKeyConstraint(['layer_id'], ['Layer.id'], name=op.f('fk_LayerDatagroup_layer_id_Layer')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('date_last_modification', sa.DateTime(), nullable=True),
    sa.Column('geouser_id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.Column('datagroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datagroup_id'], ['Datagroup.id'], name=op.f('fk_LayerItem_datagroup_id_Datagroup')),
    sa.ForeignKeyConstraint(['geouser_id'], ['Geouser.id'], name=op.f('fk_LayerItem_geouser_id_Geouser')),
    sa.ForeignKeyConstraint(['layer_id'], ['Layer.id'], name=op.f('fk_LayerItem_layer_id_Layer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItem')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemDatagroupParameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyname', sa.String(length=255), nullable=False),
    sa.Column('datagroup_id', sa.Integer(), nullable=False),
    sa.Column('datatype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['datagroup_id'], ['Datagroup.id'], name=op.f('fk_LayerItemDatagroupParameter_datagroup_id_Datagroup')),
    sa.ForeignKeyConstraint(['datatype_id'], ['Datatype.id'], name=op.f('fk_LayerItemDatagroupParameter_datatype_id_Datatype')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemDatagroupParameter')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerTag',
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['Layer.id'], name=op.f('fk_LayerTag_layer_id_Layer')),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], name=op.f('fk_LayerTag_tag_id_Tag')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_LayerTranslation_language_id_Language')),
    sa.ForeignKeyConstraint(['layer_id'], ['Layer.id'], name=op.f('fk_LayerTranslation_layer_id_Layer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerTranslation')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemDatagroupParameterTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_LayerItemDatagroupParameterTranslation_language_id_Language')),
    sa.ForeignKeyConstraint(['parameter_id'], ['LayerItemDatagroupParameter.id'], name=op.f('fk_LayerItemDatagroupParameterTranslation_parameter_id_LayerItemDatagroupParameter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemDatagroupParameterTranslation')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemDatagroupParameterValue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer_item_id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['layer_item_id'], ['LayerItem.id'], name=op.f('fk_LayerItemDatagroupParameterValue_layer_item_id_LayerItem')),
    sa.ForeignKeyConstraint(['parameter_id'], ['LayerItemDatagroupParameter.id'], name=op.f('fk_LayerItemDatagroupParameterValue_parameter_id_LayerItemDatagroupParameter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemDatagroupParameterValue')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemTag',
    sa.Column('layer_item_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layer_item_id'], ['LayerItem.id'], name=op.f('fk_LayerItemTag_layer_item_id_LayerItem')),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], name=op.f('fk_LayerItemTag_tag_id_Tag')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=255), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('layer_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_LayerItemTranslation_language_id_Language')),
    sa.ForeignKeyConstraint(['layer_item_id'], ['LayerItem.id'], name=op.f('fk_LayerItemTranslation_layer_item_id_LayerItem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemTranslation')),
    info={'bind_key': 'geotag'}
    )
    op.create_table('LayerItemDatagroupParameterValueTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('parametervalue_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], name=op.f('fk_LayerItemDatagroupParameterValueTranslation_language_id_Language')),
    sa.ForeignKeyConstraint(['parametervalue_id'], ['LayerItemDatagroupParameterValue.id'], name=op.f('fk_LayerItemDatagroupParameterValueTranslation_parametervalue_id_LayerItemDatagroupParameterValue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_LayerItemDatagroupParameterValueTranslation')),
    info={'bind_key': 'geotag'}
    )
    # ### end Alembic commands ###


def downgrade_geotag():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LayerItemDatagroupParameterValueTranslation')
    op.drop_table('LayerItemTranslation')
    op.drop_table('LayerItemTag')
    op.drop_table('LayerItemDatagroupParameterValue')
    op.drop_table('LayerItemDatagroupParameterTranslation')
    op.drop_table('LayerTranslation')
    op.drop_table('LayerTag')
    op.drop_table('LayerItemDatagroupParameter')
    op.drop_table('LayerItem')
    op.drop_table('LayerDatagroup')
    op.drop_table('Tag')
    op.drop_table('Layer')
    op.drop_table('Datagroup')
    op.drop_table('Visibility')
    op.drop_table('Language')
    op.drop_table('Geouser')
    op.drop_table('Datatype')
    op.drop_table('Contribution')
    # ### end Alembic commands ###


def upgrade_data_versions():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_street',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_street')),
    info={'bind_key': 'data_versions'}
    )
    op.create_table('graph_water',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_water')),
    info={'bind_key': 'data_versions'}
    )
    op.create_table('tide_new',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_station', sa.String(length=8), nullable=True),
    sa.Column('station', sa.String(length=64), nullable=True),
    sa.Column('short_name', sa.String(length=16), nullable=True),
    sa.Column('latDMSN', sa.Float(), nullable=True),
    sa.Column('lonDMSE', sa.Float(), nullable=True),
    sa.Column('latDDN', sa.Float(), nullable=True),
    sa.Column('lonDDE', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tide_new')),
    info={'bind_key': 'data_versions'}
    )
    op.create_table('graph_waterbus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('gtfs_number', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('graph_street_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['graph_street_id'], ['graph_street.id'], name=op.f('fk_graph_waterbus_graph_street_id_graph_street'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_waterbus')),
    info={'bind_key': 'data_versions'}
    )
    op.create_table('current_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_graph_id', sa.Integer(), nullable=True),
    sa.Column('waterbus_graph_id', sa.Integer(), nullable=True),
    sa.Column('water_graph_id', sa.Integer(), nullable=True),
    sa.Column('tide_id', sa.Integer(), nullable=True),
    sa.Column('graph_updated_at', sa.DateTime(), nullable=True),
    sa.Column('graph_check_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['street_graph_id'], ['graph_street.id'], name=op.f('fk_current_data_street_graph_id_graph_street')),
    sa.ForeignKeyConstraint(['tide_id'], ['tide_new.id'], name=op.f('fk_current_data_tide_id_tide_new')),
    sa.ForeignKeyConstraint(['water_graph_id'], ['graph_water.id'], name=op.f('fk_current_data_water_graph_id_graph_water')),
    sa.ForeignKeyConstraint(['waterbus_graph_id'], ['graph_waterbus.id'], name=op.f('fk_current_data_waterbus_graph_id_graph_waterbus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_current_data')),
    info={'bind_key': 'data_versions'}
    )
    # ### end Alembic commands ###


def downgrade_data_versions():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_data')
    op.drop_table('graph_waterbus')
    op.drop_table('tide_new')
    op.drop_table('graph_water')
    op.drop_table('graph_street')
    # ### end Alembic commands ###

